name: 📚 User Story
description: Template for creating a user story with acceptance criteria
title: "[Story]: "
labels: [user story]
body:
  - type: input
    id: role
    attributes:
      label: As a
      placeholder: e.g., supply chain manager

  - type: input
    id: need
    attributes:
      label: I need
      placeholder: e.g., to optimize delivery routes

  - type: input
    id: benefit
    attributes:
      label: So that
      placeholder: e.g., I can reduce delivery time

  - type: markdown
    attributes:
      value: |
        ---
        ### Summary

        **As a** ${{ inputs.role }}  
        **I need** ${{ inputs.need }}  
        **So that** ${{ inputs.benefit }}

  - type: textarea
    id: details
    attributes:
      label: Details and Assumptions
      description: Add any known information, notes, or assumptions here.
      placeholder: "* Document what you know..."

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: Define done-ness using Gherkin syntax.
      value: |
        ```gherkin
        Given [some context]
        When [certain action is taken]
        Then [the outcome of action is observed]
        ```
